FTL Keys (Updated)
MetalSage/space-station-14 pull request #96
Opened 2024-01-26 14:05 UTC by Fragoler

## О PR
Блюспейс ключи. Трейд пост и КТ вынесено на отдельные БС точки.

## Технические детали
Затронуты файлы оффов: 
- EmergencySystem: FTLDestination не выдается, используется маркеры
- ShuttleSystem: Добавлен компонент для спавна карт Раундстартом

Маркеры:
Маркеры, при постановке изменяют FTLWhitelist грида. Расставлены на всех картах, КТ, ЦК, Трейдпосте, Планете Ядерных Оперов. Весь контроль вайтлиста - через них.

## Медиа

**Changelog**

<!--
Убедитесь, что вы убрали этот шаблон Changelog из блока комментариев, чтобы он отображался.
:cl:
- add: Добавлена радость!
- remove: Удалено развлечение!
- tweak: Изменено развлечение!
- fix: Исправлено развлечение!

2024-01-26 15:09 UTC, Lokilife requested changes

2024-01-26 15:09 UTC, Lokilife commented on Content.Shared/Stories/FTLKeys/Systems/ConsoleLockSystem.cs
> +public sealed class ConsoleLockSystem : EntitySystem
А зачем делать велосипед если уже есть LockComponent и LockSystem? В чём отличия?

2024-01-26 15:09 UTC, Lokilife commented on Content.Server/Stories/Shuttles/Components/MapSpawnComponent.cs
> +    public ComponentRegistry AddComponents = new();
Для чего это нужно?

2024-01-26 16:24 UTC, Fragoler commented on Content.Shared/Stories/FTLKeys/Systems/ConsoleLockSystem.cs
> +public sealed class ConsoleLockSystem : EntitySystem
Компонент Lock планировался в применении для шкафов, в нём прописано смена Appearance в каждом состоянии. ConsoleLock - обрезанная версия

2024-01-26 16:25 UTC, Fragoler commented on Content.Server/Stories/Shuttles/Components/MapSpawnComponent.cs
> +    public ComponentRegistry AddComponents = new();
Способ выдавать компонент гриду при его спавне

2024-01-27 06:49 UTC, Fragoler commented on Content.Server/Stories/FTLKey/System/FTLAccessConsoleSystem.cs
> +            TryComp<TransformComponent>(uid, out var xform);
Исправлено

2024-01-27 06:49 UTC, Fragoler commented on Content.Server/Stories/FTLKey/System/FTLAccessConsoleSystem.cs
> +            if (xform is null || xform.GridUid is null)
Переписал

2024-01-27 06:50 UTC, Fragoler commented on Content.Server/Stories/FTLKey/System/FTLAccessConsoleSystem.cs
> +        private TagComponent? GetTagComp(EntityUid uid)
Не заметил после очередного переписывания. Исправил.

2024-01-27 06:50 UTC, Fragoler commented on Content.Server/Stories/FTLKey/System/FTLAccessConsoleSystem.cs
> +            RemComp<TagComponent>((EntityUid) xform.GridUid);
Переделал

2024-01-27 06:50 UTC, Fragoler commented on Content.Server/Stories/FTLKey/Components/FTLAccessConsoleComponent.cs
Переделал на Dictionary

2024-01-27 06:50 UTC, Fragoler commented on Content.Server/Stories/FTLKey/System/FTLAccessConsoleSystem.cs
> +            if (tagComponent is null) return;
Логично, исправил.

2024-01-27 06:50 UTC, Fragoler commented on Content.Server/Stories/FTLKey/System/FTLAccessConsoleSystem.cs
> +                if (keyComp is null) return;
Сделано

2024-01-27 06:51 UTC, Fragoler commented on Content.Server/Stories/FTLKey/Components/FTLAccessConsoleComponent.cs
> +    [ViewVariables] public EntityUid FTLKeyA = EntityUid.Invalid;
Убрал лишнее из FTLAccessConsoleComponent

2024-01-27 06:51 UTC, Fragoler commented on Content.Server/Stories/Shuttles/Components/MapSpawnComponent.cs
> +    public MapSpawnGroup()
Нужно было для обломков. Убрал

2024-01-27 06:51 UTC, Fragoler commented on Content.Server/Stories/Shuttles/Systems/MapSpawnSystem.cs
> +                if (!valid)
Несуразность. Убрал

2024-01-27 06:52 UTC, Fragoler commented on Content.Shared/Stories/FTLKeys/Systems/ConsoleLockSystem.cs
> +            _sharedPopupSystem.PopupClient(Loc.GetString("lock-comp-has-user-access-fail"), uid, user);
Знаю. Это осталось от Официального разработчика. Исправил

2024-01-27 06:52 UTC, Fragoler commented on Content.Shared/Stories/FTLKeys/Systems/ConsoleLockSystem.cs
> +        RemComp<ConsoleLockComponent>(uid); //Literally destroys the lock as a tell it was emagged
Переделал систему емага.

2024-01-27 18:03 UTC, Lokilife requested changes

2024-01-27 18:03 UTC, Lokilife commented on Content.Shared/Stories/FTLKeys/Systems/ConsoleLockSystem.cs
> +public sealed class ConsoleLockSystem : EntitySystem
Он используется также для канистр газа и для блокировки шкафа для пожарного топора. И у последнего спрайт также не меняется от состояния заблокирован/разблокирован. Вырезай.

2024-01-27 18:03 UTC, Lokilife commented on Resources/Maps/Stories/atlas.yml
> +        ShuttleConsole-FTLKeySlotA: !type:ContainerSlot
Под словари переписал, а прототипы поменять забыл.

2024-01-28 06:15 UTC, Fragoler commented on Content.Shared/Stories/FTLKeys/Systems/ConsoleLockSystem.cs
> +public sealed class ConsoleLockSystem : EntitySystem
Стандартный компонент при нажатии на консоль автоматически пытается ее открыть, и не даёт пилотировать шаттл, если нет доступа командования. 

В LoсkSystem встроен обработчик ивента нажатия на консоль, который прерывает ивент

2024-01-28 09:48 UTC, Fragoler commented on Content.Server/Stories/Shuttles/Components/MapSpawnComponent.cs
> +    public ComponentRegistry AddComponents = new();
Исправил

2024-01-28 09:48 UTC, Fragoler commented on Resources/Maps/Stories/atlas.yml
> +        ShuttleConsole-FTLKeySlotA: !type:ContainerSlot
Убрал эти вещи из сохранений

2024-01-31 16:57 UTC, Lokilife commented on Content.Shared/Stories/FTLKeys/Systems/ConsoleLockSystem.cs
> +public sealed class ConsoleLockSystem : EntitySystem
Может тогда доработаешь LockSystem чем будешь велосипеды делать?

2024-02-10 15:48 UTC, closed without merging